### ISSUE TITLE
Data Availability

### ISSUE THREAD

**Issue by isCopyman** [sltzgs/Wind_Turbine_SCADA_open_data#1]
Thank you for your contribution. May I ask if you can access this address [Engie "La Haute Borne" wind farm](https://opendata-renewables.engie.com/) I seem to be unable to access it. It would be even better if you could provide all of these data on GitHub.

**Comment by minimrbanana** [comment]
Same, I can not access it either.

**Comment by sltzgs** [comment]
Hey,
Thanks for raising attention to that. Indeed, it seems like Engie has removed its "Haute Borne" dataset from the web. However, I cannot upload/share the data, since it is owned by Engie. I have put a respective remark in the table.
